Improve calibration workflow

diff --git a/.github/workflows/calibration.yml b/.github/workflows/calibration.yml
--- a/.github/workflows/calibration.yml
+++ b/.github/workflows/calibration.yml
@@ -32,11 +32,27 @@ jobs:
       run: sleep 5
 
     - name: Test Lambda Function with curl
+      id: test-lambda
       run: |
         cd ../sdc_aws_processing_lambda
-        curl -XPOST "http://localhost:9000/2015-03-31/functions/function/invocations" -d @lambda_function/tests/test_data/test_eea_event.json
+        # Run curl and write the HTTP status code to a variable
+        HTTP_STATUS=$(curl -X POST "http://localhost:9000/2015-03-31/functions/function/invocations" \
+                      -d @lambda_function/tests/test_data/test_eea_event.json \
+                      -o response.json -w '%{http_code}')
+    
+        # Check if the HTTP status is 200 (OK)
+        if [ "$HTTP_STATUS" -eq 200 ]; then
+          echo "Success: HTTP status is 200"
+          echo "test_success=true" >> $GITHUB_OUTPUT
+          exit 0  # Exit with success
+        else
+          echo "Error or unexpected HTTP status: $HTTP_STATUS"
+          echo "test_success=false" >> $GITHUB_OUTPUT
+          exit 1  # Exit with failure
+        fi
 
     - name: Copy Processed Files from Container
+      if: steps.test-lambda.outputs.test_success == 'true'
       run: |
         container_id=$(docker ps -qf "ancestor=processing_function:latest")
         # Create a directory for processed files
@@ -46,15 +62,18 @@ jobs:
 
     - name: Upload Processed Files as Artifact
       id: artifact-upload-step
+      if: steps.test-lambda.outputs.test_success == 'true'
       uses: actions/upload-artifact@v4
       with:
           name: processed-files
           path: processed_files/
 
     - name: Echo Artifact URL
+      if: steps.test-lambda.outputs.test_success == 'true'
       run: echo "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.artifact-upload-step.outputs.artifact-id }}"
     
     - name: Comment PR
+      if: steps.test-lambda.outputs.test_success == 'true'
       uses: thollander/actions-comment-pull-request@v2
       # Only comment if triggered by a pull request target event
       with:
